#!/bin/sh
#
# SLURM HEADER
#############################################
# JOB INFO
#SBATCH --account=emm4
#SBATCH --time=00-00:15:00
#SBATCH --job-name=Virathon_CheckV_Polaribacter
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=1G
#SBATCH --output=/mnt/lustre/scratch/fcoutinho/Polaribacter/jobLog_%J.out
#SBATCH --error=/mnt/lustre/scratch/fcoutinho/Polaribacter/jobLog_%J.err
#SBATCH --mail-type=END
#SBATCH --mail-user=felipehcoutinho@gmail.com

##############################################
module load python/3.8.5
module load blast/2.7.1

python3 /mnt/lustre/bio/users/fcoutinho/Scripts/virathon_v0.1.py --genome_files /mnt/lustre/scratch/fcoutinho/Polaribacter/Polaribacter_Phage_Genomes.fasta --make_pops True --threads 24