#!/bin/sh
#
# SLURM HEADER
#############################################
# JOB INFO
#SBATCH --account=emm4
#SBATCH --time=00-06:00:00
#SBATCH --job-name=Virathon_VIBRANT_Malaspina
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=15G
#SBATCH --output=/mnt/lustre/scratch/fcoutinho/Malaspina_Virus/jobLog_%J.out
#SBATCH --error=/mnt/lustre/scratch/fcoutinho/Malaspina_Virus/jobLog_%J.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=felipehcoutinho@gmail.com

##############################################
module load python/3.8.5
module load vibrant


python3 /mnt/lustre/bio/users/fcoutinho/Scripts/virathon_v0.1.py --genome_files /mnt/lustre/repos/bio/projects/malaspina/release1/MAGs/01_bathypelagic-MAGs-JGI/00_co-assembly/01_jgi-co-assembly-megahit.meta-large.k27-87step10.contigs.fasta --call_vibrant True --threads 24
